# Generated by Django 2.1 on 2018-08-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabus_text', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('proposed_date_completeion', models.DateField()),
                ('completion_status', models.IntegerField(default=0)),
            ],
        ),
    ]
